### ISSUE TITLE
Direct Message PFP's are on the Persons Name

### ISSUE THREAD

**Issue by GrayGray72** [rauenzi/Nox#11]
anyone know a temp fix for this... or can the author fix this  
![Untitled2](https://user-images.githubusercontent.com/49378176/61971361-e738b600-afac-11e9-9427-01b3a9749aa6.png)

Another issue you can see is the icons under the home title bar are improperly sized and the text under them clips with the background

**Comment by HYPExMon5ter** [comment]
having the same issue, new discord update screwed up quite a bit of things in this theme.

**Comment by itsTyrion** [comment]
Join the Nox Discord guild: There's a temp fix: (Taken from there)
```css
/*TEMP FIX (for broken avatars) STABLE*/
.avatar-17mtNa {
    position: relative;
}
```
Paste as custom CSS and save. This fixes the PFPs on the name
