### ISSUE TITLE
Doesn't affect channel list

### ISSUE THREAD

**Issue by kilbouri** [rauenzi/Nox#26]
Yea, the channel list doesn't get themed.
![image](https://user-images.githubusercontent.com/52428953/99484513-916ce780-292e-11eb-81db-20fb6f82334a.png)

**Comment by kilbouri** [comment]
Resolved with a bit of custom CSS on top (using BetterDiscord's normalized tags). It would be nice, however, to see this integrated into the theme itself. I don't want to touch the source, I'll probably break it somehow.
```css
.da-sidebar {
    --background-secondary: var(--nox-level2);
}
.container-1taM1r {
    background-color: var(--nox-level3);
}
```
![image](https://user-images.githubusercontent.com/52428953/99485067-b0b84480-292f-11eb-8fe6-f5eb844b925f.png)
[Edit: added image]
