### ISSUE TITLE
Emoji Bar is bugged

### ISSUE THREAD

**Issue by yuma42u19** [rauenzi/Nox#30]
![grafik](https://user-images.githubusercontent.com/79582349/109002597-b64bc600-76a6-11eb-9b3d-74458bd4fe07.png)

Is it my fault or is it a bug for everyone?

**Comment by yuma42u19** [comment]
it is very long for some reason.

**Comment by crxts** [comment]
tempfix: 
```css
.layer-v9HyYc section {
    background: transparent !important;
}
```
